### ISSUE TITLE
catkin_make

### ISSUE THREAD

**Issue by hz-ants** [sdwyc/frontier_exploration_occupancygrid#1]
Missing duing compilation:  #include frontier_exploration/PointArray.h  #include frontier_exploration/get_centroids.h,how to solve it?thank you

**Comment by sdwyc** [comment]
> Missing duing compilation: #include frontier_exploration/PointArray.h #include frontier_exploration/get_centroids.h,how to solve it?thank you

Hi! It seems like .msg file is not built. You can try to build the whole package repeatedly.

**Comment by hz-ants** [comment]
![Screenshot from 2024-03-23 19-44-03](https://github.com/sdwyc/frontier_exploration_occupancygrid/assets/51619755/3d5d5de3-7f21-4e49-a41b-8fd961e29add)
